---

- name: Debian | install multimedia repo key
  apt_key: keyserver=keyserver.ubuntu.com id=5C808C2B65558117

- name: Debian | add multimedia repo
  template:
    src: "debian/multimedia.list.j2"
    dest: "/etc/apt/sources.list.d/multimedia.list"
    owner: root
    group: root
    mode: 0644
  notify:
  - Debian | update package cache

- name: Debian | install multimedia repo keys package
  apt:
    name: deb-multimedia-keyring
    update_cache: yes
    state: present
