---

- name: Debian | install mariadb old repo key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
  when: ansible_lsb.codename in [ "wheezy", "jessie" ]

- name: Debian | install mariadb new repo key
  apt_key: keyserver=keyserver.ubuntu.com id=0xF1656F24C74CD1D8
  when: ansible_lsb.codename in [ "stretch" ]

- name: Debian | add mariadb 5.5 repo
  copy:
    content: "deb http://mirror.netcologne.de/mariadb/repo/5.5/debian {{ ansible_lsb.codename }} main"
    dest: "/etc/apt/sources.list.d/mariadb55.list"
  when: ansible_lsb.codename in [ "wheezy" ]
  notify:
  - Debian | update package cache

- name: Debian | add mariadb 10.5 repo
  copy:
    content: "deb http://mirror.netcologne.de/mariadb/repo/10.5/debian {{ ansible_lsb.codename }} main"
    dest: "/etc/apt/sources.list.d/mariadb105.list"
  notify:
  - Debian | update package cache
