---

- name: Debian | reset sources.list (<v8)
  template:
    src: "debian/sources.list.archive.j2"
    dest: "/etc/apt/sources.list"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int < 8
  notify:
  - Debian | update package cache

- name: Debian | reset sources.list (=v8)
  template:
    src: "debian/sources.list.jessie.j2"
    dest: "/etc/apt/sources.list"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int == 8
  notify:
  - Debian | update package cache


- name: Debian | reset sources.list (>v8)
  template:
    src: "debian/sources.list.current.j2"
    dest: "/etc/apt/sources.list"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int > 8
  notify:
  - Debian | update package cache

- name: Debian | install official repos keys
  apt:
    name:
    - debian-keyring
    - debian-archive-keyring
    update_cache: yes
    state: present
  notify:
  - Debian | update package cache

- name: Debian | add backports repo (>v8)
  copy:
    content: "deb http://ftp.debian.org/debian/ {{ ansible_lsb.codename }}-backports main contrib non-free"
    dest: "/etc/apt/sources.list.d/backports.list"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int > 8
  notify:
  - Debian | update package cache

- name: Debian | remove backports repo (<=v8)
  file:
    path: "/etc/apt/sources.list.d/backports.list"
    state: absent
  when: ansible_distribution_major_version|int <= 8
  notify:
  - Debian | update package cache

- name: Debian | Multimedia repo
  include: debian_multimedia.yml
  when: debian_multimedia and ansible_distribution_major_version|int >= 7

- name: Debian | Dotdeb repo
  include: debian_dotdeb.yml
  when: debian_dotdeb and ansible_distribution_major_version|int >= 7

- name: Debian | Nginx repo
  include: debian_nginx.yml
  when: debian_nginx and ansible_distribution_major_version|int >= 7

- name: Debian | MariaDB repo
  include: debian_mariadb.yml
  when: debian_mariadb and ansible_distribution_major_version|int >= 7
