---

- name: Debian | versions up to 8
  block:

  - name: Debian | disable validity checks (<=v8)
    copy:
      content: 'Acquire::Check-Valid-Until "false";'
      dest: "/etc/apt/apt.conf.d/100disablechecks"
      owner: root
      group: root
      mode: 0644
    notify:
    - Debian | update package cache

  - name: Debian | reset sources.list (<=v8)
    template:
      src: "debian/sources.list.archive.j2"
      dest: "/etc/apt/sources.list"
      owner: root
      group: root
      mode: 0644
    notify:
    - Debian | update package cache

  - name: Debian | remove backports repo (<=v8)
    file:
      path: "/etc/apt/sources.list.d/backports.list"
      state: absent
    notify:
    - Debian | update package cache

  when: ansible_distribution_major_version|int <= 8

- name: Debian | versions higher than 8
  block:

  - name: Debian | install APT HTTPS support
    apt:
      name:
      - apt-transport-https
      state: present

  - name: Debian | reset sources.list (>v8)
    template:
      src: "debian/sources.list.current.j2"
      dest: "/etc/apt/sources.list"
      owner: root
      group: root
      mode: 0644
    notify:
    - Debian | update package cache

  - name: Debian | add backports repo (>v8)
    copy:
      content: "deb https://deb.debian.org/debian {{ ansible_lsb.codename }}-backports main contrib non-free"
      dest: "/etc/apt/sources.list.d/backports.list"
      owner: root
      group: root
      mode: 0644
    notify:
    - Debian | update package cache

  when: ansible_distribution_major_version|int > 8

- name: Debian | install official repos keys
  apt:
    name:
    - debian-keyring
    - debian-archive-keyring
    allow_unauthenticated: yes
    update_cache: yes
    state: present
  notify:
  - Debian | update package cache

- name: Debian | Multimedia repo
  include: debian_multimedia.yml
  when: debian_multimedia and ansible_distribution_major_version|int >= 7

- name: Debian | Dotdeb repo
  include: debian_dotdeb.yml
  when: debian_dotdeb and ansible_distribution_major_version|int >= 7

- name: Debian | Nginx repo
  include: debian_nginx.yml
  when: debian_nginx and ansible_distribution_major_version|int >= 7

- name: Debian | MariaDB repo
  include: debian_mariadb.yml
  when: debian_mariadb and ansible_distribution_major_version|int >= 7
