---

- name: Debian | archived versions (up to 8)
  block:

  - name: Debian | disable validity checks (<=v8)
    copy:
      content: 'Acquire::Check-Valid-Until "false";'
      dest: "/etc/apt/apt.conf.d/100disablechecks"
      owner: root
      group: root
      mode: 0644
    notify:
    - Debian | update package cache

  - name: Debian | reset sources.list (<=v7)
    template:
      src: "debian/sources.list.archive.j2"
      dest: "/etc/apt/sources.list"
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution_major_version|int <= 7
    notify:
    - Debian | update package cache

  - name: Debian | reset sources.list (==v8)
    template:
      src: "debian/sources.list.oldoldstable.j2"
      dest: "/etc/apt/sources.list"
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution_major_version|int == 8
    notify:
    - Debian | update package cache

  - name: Debian | add backports repo (<=v8)
    copy:
      content: "deb http://archive.debian.org/debian {{ ansible_lsb.codename }}-backports main contrib non-free\ndeb http://archive.debian.org/debian {{ ansible_lsb.codename }}-backports-sloppy main contrib non-free\n"
      dest: "/etc/apt/sources.list.d/backports.list"
      owner: root
      group: root
      mode: 0644
    notify:
    - Debian | update package cache

  when: ansible_distribution_major_version|int <= 8

- name: Debian | current versions (from 9 on)
  block:

  - name: Debian | reset sources.list (>=v9)
    template:
      src: "debian/sources.list.current.j2"
      dest: "/etc/apt/sources.list"
      owner: root
      group: root
      mode: 0644
    notify:
    - Debian | update package cache

  - name: Debian | add backports repo (>=v9)
    copy:
      content: "deb https://deb.debian.org/debian {{ ansible_lsb.codename }}-backports main contrib non-free"
      dest: "/etc/apt/sources.list.d/backports.list"
      owner: root
      group: root
      mode: 0644
    notify:
    - Debian | update package cache

  when: ansible_distribution_major_version|int >= 9

- name: Debian | install APT HTTPS support
  apt:
    name:
    - apt-transport-https
    allow_unauthenticated: yes
    update_cache: yes
    state: present

- name: Debian | install official repos keys
  apt:
    name:
    - debian-keyring
    - debian-archive-keyring
    allow_unauthenticated: yes
    update_cache: yes
    state: present
  notify:
  - Debian | update package cache

- name: Debian | Multimedia repo
  include: debian_multimedia.yml
  when: debian_multimedia and ansible_distribution_major_version|int >= 8

- name: Debian | Dotdeb repo
  include: debian_dotdeb.yml
  when: debian_dotdeb and ansible_distribution_major_version|int >= 7
  
  - name: Debian | Nginx repo
  include: debian_nginx.yml
  when: debian_nginx and ansible_distribution_major_version|int >= 7

- name: Debian | MariaDB repo
  include: debian_mariadb.yml
  when: debian_mariadb and ansible_distribution_major_version|int >= 7
