---

- name: add dotdeb repo key
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg state=present validate_certs=no
  when: ansible_distribution_major_version|int >= 6

- name: add dotdeb repo
  copy:
    content: "deb http://packages.dotdeb.org {{ ansible_lsb.codename }} all"
    dest: "/etc/apt/sources.list.d/dotdeb.list"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int >= 6
