---

- name: Debian | reset sources.list (<v7)
  template:
    src: "debian/sources.list.old.j2"
    dest: "/etc/apt/sources.list"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int < 7

- name: Debian | reset sources.list (>=v7)
  template:
    src: "debian/sources.list.new.j2"
    dest: "/etc/apt/sources.list"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int >= 7

- name: Debian | install official repos keys
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - debian-keyring
    - debian-archive-keyring

- name: Debian | add backports repo
  copy:
    content: "deb http://ftp.debian.org/debian/ {{ ansible_lsb.codename }}-backports main contrib non-free"
    dest: "/etc/apt/sources.list.d/backports.list"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int >= 7

- name: Debian | Multimedia repo
  include: debian_multimedia.yml
  when: debian_multimedia and ansible_distribution_major_version|int >= 7

- name: Debian | Dotdeb repo
  include: debian_dotdeb.yml
  when: debian_dotdeb and ansible_distribution_major_version|int >= 7

- name: Debian | Nginx repo
  include: debian_nginx.yml
  when: debian_nginx and ansible_distribution_major_version|int >= 7

- name: Debian | MariaDB repo
  include: debian_mariadb.yml
  when: debian_mariadb and ansible_distribution_major_version|int >= 7
