---

- name: Debian | install mariadb repo key
  apt_key:
    url: "https://mariadb.org/mariadb_release_signing_key.asc"
    state: present

- name: Debian | add mariadb 10.4 repo
  copy:
    content: "deb http://mirror.netcologne.de/mariadb/repo/10.4/debian {{ ansible_lsb.codename }} main"
    dest: "/etc/apt/sources.list.d/mariadb104.list"
  when: ansible_lsb.codename in [ "wheezy" ]
  notify:
  - Debian | update package cache

- name: Debian | add mariadb 10.5 repo
  copy:
    content: "deb http://mirror.netcologne.de/mariadb/repo/10.5/debian {{ ansible_lsb.codename }} main"
    dest: "/etc/apt/sources.list.d/mariadb105.list"
    when: debian_multimedia and ansible_distribution_major_version|int >= 8
  notify:
  - Debian | update package cache
