---

- name: install mariadb repo key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
  when: ansible_distribution_major_version|int == 7 

- name: add mariadb repo
  copy:
    content: "deb http://mirror.netcologne.de/mariadb/repo/5.5/debian wheezy main"
    dest: "/etc/apt/sources.list.d/mariadb.list"
  when: ansible_distribution_major_version|int == 7
