---

- name: Debian | add dotdeb repo key
  apt_key:
    url: "https://www.dotdeb.org/dotdeb.gpg"
    validate_certs: false
    state: present

- name: Debian | add dotdeb repo
  copy:
    content: "deb http://packages.dotdeb.org {{ ansible_lsb.codename }} all"
    dest: "/etc/apt/sources.list.d/dotdeb.list"
    owner: root
    group: root
    mode: 0644
  notify:
  - Debian | update package cache
