---
# tasks file for mablanco.repomgmt

- name: echo info message
  debug: msg="Installing repos for a {{ ansible_distribution }} {{ ansible_lsb.codename }} ({{ ansible_distribution_version }}) distro"

- name: repos for Debian
  include: debian.yml
  when: ansible_distribution == 'Debian'

- name: repos for Ubuntu
  include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: repos for RHEL
  include: rhel.yml
  when: ansible_distribution == 'RedHat'

- name: repos for CentOS
  include: centos.yml
  when: ansible_distribution == 'CentOS'

- name: repos for Fedora
  include: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: repos for SLES
  include: sles.yml
  when: ansible_distribution == 'SLES'
