---

- name: RedHat | enable CentOS-6 Plus repo
  command: yum-config-manager --enable centosplus
  when: ansible_distribution_major_version|int == 6

- name: RedHat | enable CentOS-6 Contrib repo
  command: yum-config-manager --enable contrib
  when: ansible_distribution_major_version|int == 6

- name: RedHat | enable CentOS-7 Plus repo
  command: yum-config-manager --enable centosplus
  when: ansible_distribution_major_version|int == 7

- name: RedHat | add EPEL repo
  yum: name="http://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm" state=present
  when: rhel_epel or rhel_remi or rhel_ius

- name: RedHat | add REMI repo
  yum: name="http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm" state=present
  when: rhel_remi

- name: RedHat | enable REMI repo
  command: yum-config-manager --enable remi
  when: rhel_remi

- name: RedHat | add RPM Fusion repo (free)
  yum: name="http://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm" disable_gpg_check=yes state=present
  when: rhel_rpmfusion

- name: RedHat | add RPM Fusion repo (non-free)
  yum: name="http://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm" disable_gpg_check=yes state=present
  when: rhel_rpmfusion

- name: RedHat | add NUX Dextop repo key
  rpm_key: key="http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro" state=present
  when: rhel_nux

- name: RedHat | add NUX Dextop repo (RHEL 6)
  yum: name="http://li.nux.ro/download/nux/dextop/el6/x86_64/nux-dextop-release-0-2.el6.nux.noarch.rpm" state=present
  when: rhel_nux

- name: RedHat | add NUX Dextop repo (RHEL 7)
  yum: name="http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm" state=present
  when: rhel_nux

- name: RedHat | add NUX Misc repo
  get_url: url="http://li.nux.ro/download/nux/misc/nux-misc.repo" dest=/etc/yum.repos.d/nux-misc.repo mode=0644
  when: rhel_nux_misc

- name: RedHat | enable NUX Misc repo
  command: yum-config-manager --enable nux-misc
  when: rhel_nux_misc

- set_fact:
    ius_distribution_abbrev: "{{ (ansible_distribution == 'CentOS') | ternary('centos', 'rhel') }}"

- name: RedHat | add IUS repo
  yum: name="https://{{ ius_distribution_abbrev }}{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm" state=present
  when: rhel_ius
