---

- name: Ubuntu | reset sources.list
  template:
    src: "ubuntu/sources.list.j2"
    dest: "/etc/apt/sources.list"
    owner: root
    group: root
    mode: 0644
  notify:
  - Ubuntu | update package cache

- name: Ubuntu | install official repos keys
  apt:
    name: ubuntu-keyring
    update_cache: yes
    state: present
  notify:
  - Ubuntu | update package cache

- name: Ubuntu | Universe repo
  include: ubuntu_universe.yml
  when: ubuntu_universe

- name: Ubuntu | Multiverse repo
  include: ubuntu_multiverse.yml
  when: ubuntu_multiverse

- name: Ubuntu | Backports repo
  include: ubuntu_backports.yml
  when: ubuntu_backports

- name: Ubuntu | Partners repo
  include: ubuntu_partners.yml
  when: ubuntu_partners

- name: Ubuntu | Nginx repo
  include: ubuntu_nginx.yml
  when: ubuntu_nginx

- name: Ubuntu | MariaDB repo
  include: ubuntu_mariadb.yml
  when: ubuntu_mariadb
