---

- name: add ubuntu partner repo
  copy:
    content: "deb http://archive.ubuntu.com/ubuntu {{ ansible_lsb.codename }} partner"
    dest: "/etc/apt/sources.list.d/ubuntu-partners.list"
    owner: root
    group: root
    mode: 0644
